services:
  - type: web
    name: tailoring-shop
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn tailoring.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
