# Generated by Django 5.1.4 on 2026-01-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('Dress', 'Dress'), ('Blouse', 'Blouse'), ('Maggam', 'Maggam')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
