# Generated by Django 5.1.4 on 2026-01-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_design_category_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('Dress', 'Dress'), ('Blouse', 'Blouse'), ('Maggam', 'Maggam')], db_index=True, help_text='Select the type of clothing', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(help_text='Detailed description of the design', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(help_text="Enter the name of the design (e.g., 'Royal Anarkali')", max_length=255, verbose_name='Design Name'),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank if price is 'On Request'", max_digits=10, null=True, verbose_name='Price (₹)'),
        ),
        migrations.AlterField(
            model_name='designimage',
            name='image',
            field=models.ImageField(help_text='Upload high-quality images', upload_to='designs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo uploaded by customer', null=True, upload_to='reviews/', verbose_name='Customer Photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Check this box to show the review on the website', verbose_name='Approved?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='Review Message'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Star rating given by the customer', verbose_name='Rating (1-5)'),
        ),
    ]
